fonts:
  path: public/fonts
  css: public/sass/_fonts.scss

  families:
    cormorant-garamond:
      styles: [ 'normal', 'italic']
      weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
    eb-garamond:
      styles: [ 'normal', 'italic' ]
      weights: [ '100', '200', '300', '400', '500', '600', '700', '800', '900' ]
    lato:
      styles: [ 'normal', 'italic' ]
      weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
  formats: [ 'woff2', 'woff' ]
  subsets: [ 'latin', 'latin-ext' ]
  filename: "{id}-{weight}.{ext}"
  prefix: '../fonts'
